//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterTestForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("312")]
        public double X_putAwayPosition {
            get {
                return ((double)(this["X_putAwayPosition"]));
            }
            set {
                this["X_putAwayPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public double X_printingPosition {
            get {
                return ((double)(this["X_printingPosition"]));
            }
            set {
                this["X_printingPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308")]
        public double X_toClipPosition {
            get {
                return ((double)(this["X_toClipPosition"]));
            }
            set {
                this["X_toClipPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("275")]
        public double X_materialChangePosition {
            get {
                return ((double)(this["X_materialChangePosition"]));
            }
            set {
                this["X_materialChangePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public double Y_towerPositionsHookPush1 {
            get {
                return ((double)(this["Y_towerPositionsHookPush1"]));
            }
            set {
                this["Y_towerPositionsHookPush1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151")]
        public double Y_towerPositionsHookPush2 {
            get {
                return ((double)(this["Y_towerPositionsHookPush2"]));
            }
            set {
                this["Y_towerPositionsHookPush2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("302")]
        public double Y_towerPositionsHookPush3 {
            get {
                return ((double)(this["Y_towerPositionsHookPush3"]));
            }
            set {
                this["Y_towerPositionsHookPush3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("462")]
        public double Y_towerPositionsHookPush4 {
            get {
                return ((double)(this["Y_towerPositionsHookPush4"]));
            }
            set {
                this["Y_towerPositionsHookPush4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double Y_towerPositionsHookDisengaged1 {
            get {
                return ((double)(this["Y_towerPositionsHookDisengaged1"]));
            }
            set {
                this["Y_towerPositionsHookDisengaged1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double Y_towerPositionsHookDisengaged2 {
            get {
                return ((double)(this["Y_towerPositionsHookDisengaged2"]));
            }
            set {
                this["Y_towerPositionsHookDisengaged2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330")]
        public double Y_towerPositionsHookDisengaged3 {
            get {
                return ((double)(this["Y_towerPositionsHookDisengaged3"]));
            }
            set {
                this["Y_towerPositionsHookDisengaged3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double Y_towerPositionsHookDisengaged4 {
            get {
                return ((double)(this["Y_towerPositionsHookDisengaged4"]));
            }
            set {
                this["Y_towerPositionsHookDisengaged4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.6")]
        public double Y_towerPositionsHookPull1 {
            get {
                return ((double)(this["Y_towerPositionsHookPull1"]));
            }
            set {
                this["Y_towerPositionsHookPull1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("146")]
        public double Y_towerPositionsHookPull2 {
            get {
                return ((double)(this["Y_towerPositionsHookPull2"]));
            }
            set {
                this["Y_towerPositionsHookPull2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("293.5")]
        public double Y_towerPositionsHookPull3 {
            get {
                return ((double)(this["Y_towerPositionsHookPull3"]));
            }
            set {
                this["Y_towerPositionsHookPull3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("455")]
        public double Y_towerPositionsHookPull4 {
            get {
                return ((double)(this["Y_towerPositionsHookPull4"]));
            }
            set {
                this["Y_towerPositionsHookPull4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double Z_heightToRaiseBed {
            get {
                return ((double)(this["Z_heightToRaiseBed"]));
            }
            set {
                this["Z_heightToRaiseBed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250000")]
        public int printerBaudRate {
            get {
                return ((int)(this["printerBaudRate"]));
            }
            set {
                this["printerBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Z_layerHeight {
            get {
                return ((double)(this["Z_layerHeight"]));
            }
            set {
                this["Z_layerHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cureTime1 {
            get {
                return ((double)(this["cureTime1"]));
            }
            set {
                this["cureTime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double startingLayersCureTime {
            get {
                return ((double)(this["startingLayersCureTime"]));
            }
            set {
                this["startingLayersCureTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int numberOfStartingLayers {
            get {
                return ((int)(this["numberOfStartingLayers"]));
            }
            set {
                this["numberOfStartingLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public int X_feedrate {
            get {
                return ((int)(this["X_feedrate"]));
            }
            set {
                this["X_feedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int Y_feedrate {
            get {
                return ((int)(this["Y_feedrate"]));
            }
            set {
                this["Y_feedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int Z_feedrate {
            get {
                return ((int)(this["Z_feedrate"]));
            }
            set {
                this["Z_feedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cureTime2 {
            get {
                return ((double)(this["cureTime2"]));
            }
            set {
                this["cureTime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cureTime3 {
            get {
                return ((double)(this["cureTime3"]));
            }
            set {
                this["cureTime3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cureTime4 {
            get {
                return ((double)(this["cureTime4"]));
            }
            set {
                this["cureTime4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G91\r\nG1 X25 Z-2 \r\nG1 X-39 Z-4 \r\nG1 X14")]
        public string ShearProcess {
            get {
                return ((string)(this["ShearProcess"]));
            }
            set {
                this["ShearProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("273.5")]
        public double Z_zeroMaterial1 {
            get {
                return ((double)(this["Z_zeroMaterial1"]));
            }
            set {
                this["Z_zeroMaterial1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Z_zeroMaterial2 {
            get {
                return ((double)(this["Z_zeroMaterial2"]));
            }
            set {
                this["Z_zeroMaterial2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Z_zeroMaterial3 {
            get {
                return ((double)(this["Z_zeroMaterial3"]));
            }
            set {
                this["Z_zeroMaterial3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Z_zeroMaterial4 {
            get {
                return ((double)(this["Z_zeroMaterial4"]));
            }
            set {
                this["Z_zeroMaterial4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double X_pullOutPosition {
            get {
                return ((double)(this["X_pullOutPosition"]));
            }
            set {
                this["X_pullOutPosition"] = value;
            }
        }
    }
}
